7day_flask_v1/routes.py
import os
from datetime import datetime
from flask import Blueprint, render_template,request,Flask,redirect,url_for,session
from werkzeug.utils import secure_filename
from models import db,User,Category,Product,Cart,Manufacture
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user,login_required,current_user
from flask import current_app
app = Flask(__name__)
with app.app_context():
    UPLOAD_FOLDER = './static/uploads'
    ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}
    current_app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER


### Tạo blueprint ###
bp = Blueprint('routes', __name__)

### định tuyến  chung ###
def is_admin():
    user = current_user
    if user and user.role == 1:
        return True
    return False

@bp.route('/')
def index():
    feature_products = Product.query.filter(Product.feature == 1).limit(3).all()
    cate_of_the_month = Category.query.filter(Category.feature == 1).limit(3).all()
    return render_template('index.html',cate_of_the_month=cate_of_the_month,feature_products=feature_products)

@bp.route('/403')
def view_403():
    return render_template('403.html')

### AUTHENTICATION ###
@bp.route('/login', methods=['GET', 'POST'])
def view_login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        # Lấy người dùng và kiểm tra tồn tại
        user = User.query.filter_by(email=email).first()
        if user is None or not check_password_hash(user.password, password):
            # Thông tin đăng nhập không hợp lệ
            return redirect(url_for('routes.view_login')+ '?message=Email hoặc mật khẩu không chính xác')
        else:
            login_user(user)
            return redirect(url_for('routes.index'))

    return render_template('auth/login.html')

@bp.route('/register', methods=['GET', 'POST'])
def view_register():
    if request.method == 'POST':
        email = request.form.get('email')
        phone = request.form.get('phone')
        password = request.form.get('password')
        created_at = datetime.now()
        #kiem tra tk ton tai
        user = User.query.filter_by(email=email).first()
        if user:
            return redirect(url_for('routes.view_register')+ '?message=Địa chỉ email đã tồn tại!')
        new_user = User(email=email, phone=phone, password=generate_password_hash(password, method='pbkdf2:sha256'), role=0 ,created_at=created_at)
        db.session.add(new_user)
        db.session.commit()
        #dang nhap cho user do luon
        login_user(new_user)
        return redirect(url_for('routes.index'))
    return render_template('auth/register.html')

@bp.route('/logout')
@login_required
def logout():
    logout_user()  
    return redirect(url_for('routes.view_login'))
### contact and about ###
@bp.route('/about')
def view_about():
    return render_template('about.html')
@bp.route('/contact')
def view_contact():
    return render_template('contact.html')


########### SHOP ##########
@bp.route('/shop')
def view_shop():
    #get manufacture limit 4 with feature == 1 
    manufactures = Manufacture.query.all()[:4]
    page = request.args.get('page', 1, type=int)  # Get the page number from the query parameters
    per_page = 4  # Number of products per page

    all_product = Product.query.paginate(page=page, per_page=per_page)  # Paginate the products
    categories = Category.query.all()
    
    return render_template('shop.html', categories=categories, all_product=all_product,manufactures=manufactures)

@bp.route('/shop/<category_id>')
def view_shop_category(category_id):
    #get manufacture limit 4 with feature == 1 
    manufactures = Manufacture.query.all()[:4]
    categories = Category.query.all()
    category = Category.query.filter_by(id=category_id).first()
    products = Product.query.filter_by(category_id=category.id).all()
    return render_template('shop_category.html', category=category, products=products,categories=categories,manufactures=manufactures)

@bp.route('/product/<int:product_id>')
def detail_product(product_id):
    product = Product.query.get_or_404(product_id)
    return render_template('detail_product.html', product=product)

@bp.route('/cart')
@login_required
def view_cart():
    user = current_user
    total_cart = Cart.calculate_total_price(user.id)
    cart_items = Cart.get_all_products(user.id)
    return render_template('cart.html',user=user,cart_items=cart_items,total_cart=total_cart)

@bp.route('/cart/add/<int:product_id>')
@login_required
def add_to_cart(product_id):
    user = current_user
    product = Product.query.get(product_id)
    cart = Cart(user_id=user.id, product_id=product.id, quantity=1, price=product.price)
    db.session.add(cart)
    db.session.commit()
    return redirect(url_for('routes.view_cart'))

@bp.route('/del-cart-item/<int:item_id>')
@login_required
def del_cart_item(item_id):
    #lay cart cua user
    user_cart = Cart.query.filter_by(user_id=current_user.id).first()
    if user_cart:
        # lay san pham trong gio hang theo item_id
        item = Cart.query.filter_by(id=user_cart.id, product_id=item_id).first()
        if item:
            db.session.delete(item)
            db.session.commit()
    return redirect(url_for('routes.view_cart',message='success'))
################# SEARCH #################
@bp.route('/search', methods=['POST'])
def search():
    if request.method == 'POST':
        keyword = request.form.get('keyword')
        return redirect(url_for('routes.search_results'))
    return render_template('search.html')

@bp.route('/search/results', methods=['GET'])
def search_results():
    keyword = request.args.get('keyword')
    products = Product.search_products(keyword)
    return render_template('search.html', keyword=keyword, products=products)
################# ADMIN #################
@login_required
@bp.route('/admin')
def admin_view():
    user = current_user
    if not is_admin():
        return redirect(url_for('routes.view_403'))
    return render_template('core/admin/index.html',user=user)
### định tuyến người dùng (User) ###
@login_required
@bp.route('/users')
def user_view():
    if not is_admin():
        return redirect(url_for('routes.view_403'))
    users = User.query.all()
    return render_template('core/user/index.html',users=users)

@login_required
@bp.route('/create-user', methods=['GET', 'POST'])
def create_user_view():
    if not is_admin():
        return redirect(url_for('routes.view_403'))
    if request.method == 'POST':
        email = request.form.get('email')
        phone = request.form.get('phone')
        password = request.form.get('password')
        role = 1 if 'role' in request.form else 0
        created_at = datetime.now()
        #check !user ton tai
        user = User.query.filter_by(email=email).first()
        if user:
            return redirect(url_for('routes.create_user_view')+ '?message=User đã tồn tại')
        new_user = User(email=email, phone=phone, password=generate_password_hash(password, method='pbkdf2:sha256'), role=role ,created_at=created_at)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('routes.user_view')+ '?message=create')
    return render_template('core/user/create.html')

@login_required
@bp.route('/edit-user/<int:user_id>', methods=['GET', 'POST'])
def edit_user_view(user_id):
    if not is_admin():
        return redirect(url_for('routes.view_403'))
    user = User.query.filter_by(id=user_id).first_or_404()
    if request.method == 'POST':
        # Get information from request
        new_name = request.form.get('name')
        new_email = request.form.get('email')
        new_phone = request.form.get('phone')
        role = 1 if 'role' in request.form else 0
        # Update info user and save
        user.name = new_name
        user.email = new_email
        user.phone = new_phone
        user.role = role
        db.session.commit()
        return redirect(url_for('routes.user_view')+ '?message=update')
    return render_template('core/user/edit.html',user=user)

@login_required
@bp.route('/delete-user/<int:user_id>', methods=['POST'])
def delete_user(user_id):
    if not is_admin():
        return redirect(url_for('routes.view_403'))
    user = User.query.filter_by(id=user_id).first_or_404()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('routes.user_view', message='delete'))
### định tuyến Danh muc (Category) ###
@login_required
@bp.route('/categories')
def category_view():
    if not is_admin():
        return redirect(url_for('routes.view_403'))
    categories = Category.query.all()
    return render_template('core/category/index.html',categories=categories)

@login_required
@bp.route('/create-category', methods=['GET', 'POST'])
def create_category_view():
    if not is_admin():
        return redirect(url_for('routes.view_403'))
    if request.method == 'POST':
            name = request.form.get('name')
            image = request.files['image']
            feature = 1 if 'feature' in request.form else 0
            created_at = datetime.now()
            #upload image
            if image:
                print(image)
                filename = secure_filename(image.filename)
                image.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            new_category = Category(name=name,image=filename,feature=feature,created_at=created_at)
            db.session.add(new_category)
            db.session.commit()
            return redirect(url_for('routes.category_view')+ '?message=create')
    return render_template('core/category/create.html')

@login_required
@bp.route('/edit-category/<int:category_id>', methods=['GET', 'POST'])
def edit_category_view(category_id):
    if not is_admin():
        return redirect(url_for('routes.view_403'))

7day_flask_v1/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/templatemo.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/custom.css') }}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>
    <body>
        <!-- Header -->
        <nav class="navbar navbar-expand-lg navbar-light shadow">
            <div class="container d-flex justify-content-between align-items-center">
                <a class="navbar-brand text-success logo h1 align-self-center" href="{{url_for('routes.index')}}">
                    Esmart
                </a>
        
                <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
        
                <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
                    <div class="flex-fill">
                        <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{{url_for('routes.index')}}">Trang chủ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{url_for('routes.view_shop')}}">Cửa hàng</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{url_for('routes.view_contact')}}">Liên hệ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{url_for('routes.view_about')}}">Giới thiệu</a>
                            </li>
                            {% if current_user.is_authenticated %}
                                {% if current_user.role == 1 %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{url_for('routes.admin_view')}}">QUẢN TRỊ VIÊN</a>
                                    </li>
                                {% endif %}
                            {% endif %}
                        </ul>
                    </div>
                    <div class="navbar align-self-center d-flex">
                        {% if current_user.is_authenticated %}
                        <a class="nav-icon position-relative text-decoration-none" href="{{url_for('routes.view_cart')}}">
                            <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>
                            <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">
                                {{current_user.calculate_total_quantity(current_user.id)}}
                            </span>
                        </a>
                        {% endif %}
                        {% if current_user.is_authenticated %}
                            <a href="{{ url_for('routes.logout') }}">
                                <i class="fa-solid fa-right-from-bracket"></i>  
                            </a>
                        {% else %}
                            <a href="{{ url_for('routes.view_login') }}">
                                <i class="fa-solid fa-right-to-bracket"></i>
                            </a>
                        {% endif %}
                    </div>
                </div>
        
            </div>
        </nav>
        <div class="container">
          <!--  Wrapper content -->
            {% block content %}{% endblock content %}
          <!-- Start Footer -->
        <footer class="bg-dark" id="tempaltemo_footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 pt-5">
                        <h2 class="h2 text-success border-bottom pb-3 border-light logo">Esmart Shop</h2>
                        <ul class="list-unstyled text-light footer-link-list">
                            <li>
                                <i class="fa fa-phone fa-fw"></i>
                                <a class="text-decoration-none" href="tel:000-000-0000">0877202678</a>
                            </li>
                            <li>
                                <i class="fa fa-envelope fa-fw"></i>
                                <a class="text-decoration-none" href="mailto:info@company.com">2021050878@humg.edu.vn</a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-md-4 pt-5">
                        <h2 class="h2 text-light border-bottom pb-3 border-light">Địa chỉ</h2>
                        <ul class="list-unstyled text-light footer-link-list">
                            <li>
                                <i class="fas fa-map-marker-alt fa-fw"></i>
                                Thành phố Hà Nội
                            </li>
                            <li>
                                <i class="fas fa-map-marker-alt fa-fw"></i>
                                Thành phố Hồ Chí Minh
                            </li>
                        </ul>
                    </div>

                    <div class="col-md-4 pt-5">
                        <h2 class="h2 text-light border-bottom pb-3 border-light">Thông tin thêm</h2>
                        <ul class="list-unstyled text-light footer-link-list">
                            <li><a class="text-decoration-none" href="#">Trang chủ</a></li>
                            <li><a class="text-decoration-none" href="{{url_for('routes.view_about')}}">Về chúng tôi</a></li>
                            <li><a class="text-decoration-none" href="{{url_for('routes.view_contact')}}">Liên hệ</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        </div>
        <script src="{{url_for('static',filename='js/query-1.11.0.min.js')}}"></script>
        <script src="{{url_for('static',filename='js/jquery-migrate-1.2.1.min.js')}}"></script>
        <script src="{{url_for('static',filename='js/bootstrap.bundle.min.js')}}"></script>
        <script src="{{url_for('static',filename='js/js/templatemo.js')}}"></script>
        <script src="{{url_for('static',filename='js/custom.js')}}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>

7day_flask_v1/templates/search.html
{% extends "base.html" %}
<style>
    .card {
        width: 300px;
        height: 500px;
    }

</style>
{% block content %}
<div class="container-fluid">
    <div class="alert alert-dark text-center mt-3" style="color: #FFF; text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.3);" role="alert">
        Results for {{keyword}}
      </div>
    <div class="row mt-2">
        {% if products %}
        {% for data in products %}
        <div class="col-md-3">
            <div class="card mb-4 product-wap rounded-0">
                <!-- Nội dung card -->
                <div class="card rounded-0">
                    <img class="card-img rounded-0 img-fluid" src="{{ url_for('static', filename='uploads/' + data.image) }}" 
                    alt="Ảnh sản phẩm" style="width: 250px; height: 250px;object-fit: contain;">
                    <div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                        <ul class="list-unstyled">
                            <li>
                                <a class="btn btn-success text-white mt-2" href="{{url_for('routes.detail_product',product_id=data.id)}}"><i class="far fa-eye"></i></a>
                            </li>
                            <li>
                                <a class="btn btn-success text-white mt-2"
                                    href="{{url_for('routes.add_to_cart',product_id=data.id)}}"><i class="fas fa-cart-plus"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="card-body">
                    <a href="shop-single.html" class="h3 text-decoration-none">{{data.name}}</a>
                    <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                        {{data.category.get_name()}}
                    </ul>
                    <ul class="list-unstyled d-flex justify-content-center mb-1">
                        <li>
                            <i class="text-warning fa fa-star"></i>
                            <i class="text-warning fa fa-star"></i>
                            <i class="text-warning fa fa-star"></i>
                            <i class="text-warning fa fa-star"></i>
                            <i class="text-warning fa fa-star"></i>
                        </li>
                    </ul>
                    <p class="text-center mb-0">{{data.price}} VND</p>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="no-results bg-light d-flex justify-content-center align-items-center" style="height: 75vh; border-radius: 5px;">
            <p style="font-size: 24px;">No results found.</p>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

7day_flask_v1/templates/shop.html
{% extends "base.html" %}
{% block content %}
    <!-- Start Content -->
    <div class="container py-5">
        <div class="row">
            <!-- sidebar category -->
            <div class="col-lg-3">
                <h1 class="h2 pb-4" style="font-family: 'Open Sans', Arial, sans-serif; font-weight: 600; text-transform: uppercase;">Danh mục</h1>
                <ul class="list-unstyled templatemo-accordion">
                    {% if categories %}
                        {% for data in categories %}
                            <li class="pb-3">
                                <a class="collapsed d-flex justify-content-between h3 text-decoration-none" href="{{url_for('routes.view_shop_category',category_id=data.id)}}">
                                    {{data.name}}
                                    <i class="fa-solid fa-circle-chevron-right"></i>
                                </a>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>

            <div class="col-lg-9">
                <!-- navbar -->
                <div class="row">
                    <div class="col-md-6">
                        <ul class="list-inline shop-top-menu pb-3 pt-1">
                            <form method="GET" action="{{ url_for('routes.search_results') }}">
                                <div class="input-group">
                                  <input type="text" class="form-control" name="keyword" id="inputMobileSearch" placeholder="Search ..." style="border-radius: 0; border-right: none;">
                                  <div class="input-group-text" style="background-color: transparent; border-left: none;">
                                    <button type="submit" style="background-color: transparent; border: none;">
                                      <i class="fa fa-fw fa-search" style="color: #999;"></i>
                                    </button>
                                  </div>
                                </div>
                              </form>
                        </ul>
                    </div>
                </div>
                <!-- navbar -->
                <div class="row">
                    {% if all_product %}
                    {% for data in all_product %}
                    <div class="col-md-4">
                        <div class="card mb-4 product-wap rounded-0">
                                <div class="card rounded-0">
                                    <img class="card-img rounded-0 img-fluid" src="{{ url_for('static', filename='uploads/' + data.image) }}"
                                     alt="Ảnh sản phẩm" style="object-fit: contain;height: 300px;">
                                    <div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                                        <ul class="list-unstyled">
                                            <li>
                                                <a class="btn btn-success text-white mt-2" href="{{url_for('routes.detail_product',product_id=data.id)}}"><i class="far fa-eye"></i></a>
                                            </li>
                                            <li>
                                                <a class="btn btn-success text-white mt-2"
                                                href="{{url_for('routes.add_to_cart',product_id=data.id)}}"
                                                ><i class="fas fa-cart-plus"></i></a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <a href="{{url_for('routes.detail_product',product_id=data.id)}}" class="h3 text-decoration-none">{{data.name}}</a>
                                    <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                                        <li>{{data.category.get_name()}}</li>
                                    </ul>
                                    <ul class="list-unstyled d-flex justify-content-center mb-1">
                                        <li>
                                            <i class="text-warning fa fa-star"></i>
                                            <i class="text-warning fa fa-star"></i>
                                            <i class="text-warning fa fa-star"></i>
                                            <i class="text-warning fa fa-star"></i>
                                            <i class="text-warning fa fa-star"></i>
                                        </li>
                                    </ul>
                                    <p class="text-center mb-0">{{data.price}} VND</p>
                                </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
                <!-- pagination -->
                <div class="row">
                    <ul class="pagination pagination-lg justify-content-end">
                        {% if all_product.has_prev %}
                            <li class="page-item">
                                <a class="page-link rounded-0 mr-3 shadow-sm border-top-0 border-left-0 text-dark" href="{{ url_for('routes.view_shop', page=all_product.prev_num) }}">Previous</a>
                            </li>
                        {% endif %}
                        
                        {% for num in all_product.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
                            {% if num %}
                                {% if num == all_product.page %}
                                    <li class="page-item active">
                                        <a class="page-link active rounded-0 mr-3 shadow-sm border-top-0 border-left-0" href="#">{{ num }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link rounded-0 mr-3 shadow-sm border-top-0 border-left-0 text-dark" href="{{ url_for('routes.view_shop', page=num) }}">{{ num }}</a>
                                    </li>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        
                        {% if all_product.has_next %}
                            <li class="page-item">
                                <a class="page-link rounded-0 shadow-sm border-top-0 border-left-0 text-dark" href="{{ url_for('routes.view_shop', page=all_product.next_num) }}">Next</a>
                            </li>   
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Content -->

    <!-- Start Brands -->
    <section class="bg-light py-5">
        <div class="container my-4">
            <div class="row text-center py-3">
                <div class="col-lg-6 m-auto">
                    <h1 class="h1">Thương hiệu</h1>
                    <p>
                        Các thương hiệu sản phẩm đáng chú ý
                    </p>
                </div>
                <div class="col-lg-9 m-auto tempaltemo-carousel">
                    <div class="row d-flex flex-row">
                        <!--Controls-->
                        <div class="col-1 align-self-center">
                            <a class="h1" href="#multi-item-example" role="button" data-bs-slide="prev">
                                <i class="text-light fas fa-chevron-left"></i>
                            </a>
                        </div>
                        <!--End Controls-->

                        <!--Carousel Wrapper-->
                        <div class="col">
                            <div class="carousel slide carousel-multi-item pt-2 pt-md-0" id="multi-item-example" data-bs-ride="carousel">
                                <!--Slides-->
                                <div class="carousel-inner product-links-wap" role="listbox">
                                    <!--First slide-->
                                    <div class="carousel-item active">
                                        <div class="row">
                                            {% if manufactures %}
                                                {% for data in manufactures %}
                                                <div class="col-3 p-md-5">
                                                    <a href="#">
                                                        <img class="img-fluid brand-img"
                                                        src="{{ url_for('static', filename='uploads/' + data.image) }}" alt="Brand Logo">
                                                    </a>
                                                </div>
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                    </div>
                                    <!--End First slide-->
                                </div>
                                <!--End Slides-->
                            </div>
                        </div>
                        <!--End Carousel Wrapper-->

                        <!--Controls-->
                        <div class="col-1 align-self-center">
                            <a class="h1" href="#multi-item-example" role="button" data-bs-slide="next">
                                <i class="text-light fas fa-chevron-right"></i>
                            </a>
                        </div>
                        <!--End Controls-->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--End Brands-->
{% endblock content %}