7day_flask_v1/routes.py
import os
from datetime import datetime
from flask import Blueprint, render_template,request,Flask,redirect,url_for,session
from werkzeug.utils import secure_filename
from models import db,User,Category,Product,Cart,Manufacture
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user,login_required,current_user
from flask import current_app
app = Flask(__name__)
with app.app_context():
    UPLOAD_FOLDER = './static/uploads'
    ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}
    current_app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER


### Tạo blueprint ###
bp = Blueprint('routes', __name__)

### định tuyến  chung ###
def is_admin():
    user = current_user
    if user and user.role == 1:
        return True
    return False

@bp.route('/')
def index():
    feature_products = Product.query.filter(Product.feature == 1).limit(3).all()
    cate_of_the_month = Category.query.filter(Category.feature == 1).limit(3).all()
    return render_template('index.html',cate_of_the_month=cate_of_the_month,feature_products=feature_products)

@bp.route('/403')
def view_403():
    return render_template('403.html')

### AUTHENTICATION ###
@bp.route('/login', methods=['GET', 'POST'])
def view_login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        # Lấy người dùng và kiểm tra tồn tại
        user = User.query.filter_by(email=email).first()
        if user is None or not check_password_hash(user.password, password):
            # Thông tin đăng nhập không hợp lệ
            return redirect(url_for('routes.view_login')+ '?message=Email hoặc mật khẩu không chính xác')
        else:
            login_user(user)
            return redirect(url_for('routes.index'))

    return render_template('auth/login.html')

@bp.route('/register', methods=['GET', 'POST'])
def view_register():
    if request.method == 'POST':
        email = request.form.get('email')
        phone = request.form.get('phone')
        password = request.form.get('password')
        created_at = datetime.now()
        #kiem tra tk ton tai
        user = User.query.filter_by(email=email).first()
        if user:
            return redirect(url_for('routes.view_register')+ '?message=Địa chỉ email đã tồn tại!')
        new_user = User(email=email, phone=phone, password=generate_password_hash(password, method='pbkdf2:sha256'), role=0 ,created_at=created_at)
        db.session.add(new_user)
        db.session.commit()
        #dang nhap cho user do luon
        login_user(new_user)
        return redirect(url_for('routes.index'))
    return render_template('auth/register.html')

@bp.route('/logout')
@login_required
def logout():
    logout_user()  
    return redirect(url_for('routes.view_login'))
### contact and about ###
@bp.route('/about')
def view_about():
    return render_template('about.html')
@bp.route('/contact')
def view_contact():
    return render_template('contact.html')


########### SHOP ##########
@bp.route('/shop')
def view_shop():
    #get manufacture limit 4 with feature == 1 
    manufactures = Manufacture.query.all()[:4]
    page = request.args.get('page', 1, type=int)  # Get the page number from the query parameters
    per_page = 4  # Number of products per page

    all_product = Product.query.paginate(page=page, per_page=per_page)  # Paginate the products
    categories = Category.query.all()
    
    return render_template('shop.html', categories=categories, all_product=all_product,manufactures=manufactures)

@bp.route('/shop/<category_id>')
def view_shop_category(category_id):
    #get manufacture limit 4 with feature == 1 
    manufactures = Manufacture.query.all()[:4]
    categories = Category.query.all()
    category = Category.query.filter_by(id=category_id).first()
    products = Product.query.filter_by(category_id=category.id).all()
    return render_template('shop_category.html', category=category, products=products,categories=categories,manufactures=manufactures)

@bp.route('/product/<int:product_id>')
def detail_product(product_id):
    product = Product.query.get_or_404(product_id)
    return render_template('detail_product.html', product=product)

@bp.route('/cart')
@login_required
def view_cart():
    user = current_user
    total_cart = Cart.calculate_total_price(user.id)
    cart_items = Cart.get_all_products(user.id)
    return render_template('cart.html',user=user,cart_items=cart_items,total_cart=total_cart)

@bp.route('/cart/add/<int:product_id>')
@login_required
def add_to_cart(product_id):
    user = current_user
    product = Product.query.get(product_id)
    cart = Cart(user_id=user.id, product_id=product.id, quantity=1, price=product.price)
    db.session.add(cart)
    db.session.commit()
    return redirect(url_for('routes.view_cart'))

@bp.route('/del-cart-item/<int:item_id>')
@login_required
def del_cart_item(item_id):
    #lay cart cua user
    user_cart = Cart.query.filter_by(user_id=current_user.id).first()
    if user_cart:
        # lay san pham trong gio hang theo item_id
        item = Cart.query.filter_by(id=user_cart.id, product_id=item_id).first()
        if item:
            db.session.delete(item)
            db.session.commit()
    return redirect(url_for('routes.view_cart',message='success'))
################# SEARCH #################
@bp.route('/search', methods=['POST'])
def search():
    if request.method == 'POST':
        keyword = request.form.get('keyword')
        return redirect(url_for('routes.search_results'))
    return render_template('search.html')

@bp.route('/search/results', methods=['GET'])
def search_results():
    keyword = request.args.get('keyword')
    products = Product.search_products(keyword)
    return render_template('search.html', keyword=keyword, products=products)
################# ADMIN #################
@login_required
@bp.route('/admin')
def admin_view():
    user = current_user
    if not is_admin():
        return redirect(url_for('routes.view_403'))
    return render_template('core/admin/index.html',user=user)
### định tuyến người dùng (User) ###
@login_required
@bp.route('/users')
def user_view():
    if not is_admin():
        return redirect(url_for('routes.view_403'))
    users = User.query.all()
    return render_template('core/user/index.html',users=users)

@login_required
@bp.route('/create-user', methods=['GET', 'POST'])
def create_user_view():
    if not is_admin():
        return redirect(url_for('routes.view_403'))
    if request.method == 'POST':
        email = request.form.get('email')
        phone = request.form.get('phone')
        password = request.form.get('password')
        role = 1 if 'role' in request.form else 0
        created_at = datetime.now()
        #check !user ton tai
        user = User.query.filter_by(email=email).first()
        if user:
            return redirect(url_for('routes.create_user_view')+ '?message=User đã tồn tại')
        new_user = User(email=email, phone=phone, password=generate_password_hash(password, method='pbkdf2:sha256'), role=role ,created_at=created_at)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('routes.user_view')+ '?message=create')
    return render_template('core/user/create.html')

@login_required
@bp.route('/edit-user/<int:user_id>', methods=['GET', 'POST'])
def edit_user_view(user_id):
    if not is_admin():
        return redirect(url_for('routes.view_403'))
    user = User.query.filter_by(id=user_id).first_or_404()
    if request.method == 'POST':
        # Get information from request
        new_name = request.form.get('name')
        new_email = request.form.get('email')
        new_phone = request.form.get('phone')
        role = 1 if 'role' in request.form else 0
        # Update info user and save
        user.name = new_name
        user.email = new_email
        user.phone = new_phone
        user.role = role
        db.session.commit()
        return redirect(url_for('routes.user_view')+ '?message=update')
    return render_template('core/user/edit.html',user=user)

@login_required
@bp.route('/delete-user/<int:user_id>', methods=['POST'])
def delete_user(user_id):
    if not is_admin():
        return redirect(url_for('routes.view_403'))
    user = User.query.filter_by(id=user_id).first_or_404()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('routes.user_view', message='delete'))
### định tuyến Danh muc (Category) ###
@login_required
@bp.route('/categories')
def category_view():
    if not is_admin():
        return redirect(url_for('routes.view_403'))
    categories = Category.query.all()
    return render_template('core/category/index.html',categories=categories)

@login_required
@bp.route('/create-category', methods=['GET', 'POST'])
def create_category_view():
    if not is_admin():
        return redirect(url_for('routes.view_403'))
    if request.method == 'POST':
            name = request.form.get('name')
            image = request.files['image']
            feature = 1 if 'feature' in request.form else 0
            created_at = datetime.now()
            #upload image
            if image:
                print(image)
                filename = secure_filename(image.filename)
                image.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            new_category = Category(name=name,image=filename,feature=feature,created_at=created_at)
            db.session.add(new_category)
            db.session.commit()
            return redirect(url_for('routes.category_view')+ '?message=create')
    return render_template('core/category/create.html')

@login_required
@bp.route('/edit-category/<int:category_id>', methods=['GET', 'POST'])
def edit_category_view(category_id):
    if not is_admin():
        return redirect(url_for('routes.view_403'))

7day_flask_v1/templates/core/admin/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Admin | Esmart</title>
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/adminlte.min.css') }}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img  class="animation__shake" src="{{ url_for('static', filename='img/AdminLTELogo.png') }}" alt="AdminLTELogo" height="60" width="60">
  </div>

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{{url_for('routes.index')}}" class="nav-link">Home</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
            OUT
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img  class="img-circle elevation-2" alt="User Image" src="{{ url_for('static', filename='img/AdminLTELogo.png') }}" alt="AdminLTELogo" >
        </div>
        <div class="info">
          <a href="#" class="d-block">
            Quản trị viên
          </a>
        </div>
      </div>
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Dashboard -->
          <li class="nav-item menu-open">
            <a href="#" class="nav-link ">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Users
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{url_for('routes.user_view')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View Users</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{url_for('routes.create_user_view')}}" class="nav-link"> 
                  <i class="far fa-circle nav-icon"></i>
                  <p>Create User</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-chart-pie"></i>
              <p>
                Category
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{url_for('routes.category_view')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View Category</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{url_for('routes.create_category_view')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Create Category</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-circle"></i>
              <p>
                Manufacture
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{url_for('routes.manufacture_view')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View Manufacture</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{url_for('routes.create_manufacture_view')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Create Manufacture</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-circle"></i>
              <p>
                Product
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{url_for('routes.product_view')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View Product</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{url_for('routes.create_product_view')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Craete Product</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    {% block content %}
    {% endblock content %}
  </div>

  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery <script src="plugins/jquery/jquery.min.js"></script> -->

<script src="{{url_for('static',filename='jquery/jquery.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script> -->

<script src="{{url_for('static',filename='js/bootstrap.bundle.min.js')}}"></script>

<!-- AdminLTE App <script src="dist/js/adminlte.js"></script> -->

<script src="{{url_for('static',filename='js/adminlte.js')}}"></script>
</body>
</html>

7day_flask_v1/templates/core/admin/index.html
{% extends "./core/admin/base.html" %}
{% block content %}

    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">index</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>150</h3>

                <p>New Orders</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>53<sup style="font-size: 20px">%</sup></h3>

                <p>Bounce Rate</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
              <div class="inner">
                <h3>44</h3>

                <p>User Registrations</p>
              </div>
              <div class="icon">
                <i class="ion ion-person-add"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
              <div class="inner">
                <h3>65</h3>

                <p>Unique Visitors</p>
              </div>
              <div class="icon">
                <i class="ion ion-pie-graph"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

{% endblock content %}